---
title: "HR Employee Attrition"
author: "Fraol Abebe"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library("dplyr")
library(tidyverse)
source('hwLeft.R')
source('hwRight.R')
library(gridExtra)
library(ggplot2)
```


```{r}
data <- read.csv(file = "Employee-Attrition.csv")
data

```

```{r}
data <- tibble(data)
data
```

```{r}
colnames(data)

```
```{r}
summary(data)
```

```{r}
missingData <- apply(is.na(data),2, which)
missingData
```

```{r}
?is.na
```


```{r}
colnames(data)
```

```{r}
employeeData <- select(data, c(1,2,3,5,6,7,12,13,15,16,17,18,19,20,23,24,25,29,31,32,33))
employeeData
```

```{r}
names(employeeData)[1] <- 'Age'
employeeData
```

```{r}
StatusCount<- as.data.frame.matrix(employeeData %>%
group_by(Attrition) %>%
select(Gender) %>%
table())
StatusCount
```



```{r}
colnames(employeeData)
```

```{r}
yes<-subset(employeeData,Attrition=="Yes")
no<-subset(employeeData,Attrition=="No")

yes 
no

```

```{r}
ggplot() + geom_density(aes(x=MonthlyIncome*12),size=1, colour="black", data=yes,legend= "YES") +
  geom_density(aes(x=MonthlyIncome*12),size=1, colour="red", data=no) + 
labs(x= "Annual Income", y="density", title= "Annual Income Distribution by Attrition", legend= "Yes") + hw
```

```{r}
employeeData
```


```{r}
employeeData%>%
  ggplot(aes(x=MonthlyIncome*12),size=1, colour="black", fill= Attrition)+ 
  geom_density()
  labs(x= "Annual Income", y="density", title= "Annual Income Distribution by Attrition", legend= "Yes") + hw
```


```{r}
employeeData%>%
  ggplot(aes(x=MonthlyIncome*12, fill=Attrition)) +
  geom_density(alpha=0.5, size=.7, colour="black")+ 
  labs(x= "Annual Income",
       subtitle="Distribution of Annual Income by Attrition") + hw
```

```{r}
ggplot(employeeData, aes(x=Country, y=value, fill=Region))+
  geom_bar(stat='identity')+
  facet_wrap(~measure, scales="free_y", ncol=1, labeller= variable_labeller)
```


```{r}
# ggplot(data=employeeData, aes(x = Department, y = PercentSalaryHike, fill = Attrition)) +
#   geom_bar(stat = "identity")+
#   labs(title = "Employee Turnover by Salary Hike", x="Department", y="Salary Hike Percent") + hw

ggplot(data=employeeData, aes(x = JobSatisfaction, y = PercentSalaryHike)) +
  geom_col(aes(fill=Attrition)) + facet_wrap(~Gender, ncol = 2) +
  labs(title = "Job Satisfaction to Salary Hike by Gender   ") + hw

  # geom_bar(stat = "identity")+
  # labs(title = "Employee Turnover by Salary Hike", x="Department", y="Salary Hike Percent") + hw
```
count


```{r}
ggplot(data=yes, aes(x = Department, y = mean(MonthlyIncome), fill = Gender)) +
  geom_bar(stat = "identity")+
  scale_fill_manual(values = c("pink", "blue"))
```
```{r}
prop.table(table(employeeData$Attrition, employeeData$Department ))
ggplot(data=employeeData,aes(employeeData$Gender,..count..,fill=factor(employeeData$Attrition)))+
  geom_bar(position="dodge") + hw
```

```{r}

tapply(employeeData$Attrition, employeeData$OverTime, mean)
```


```{r}
ggplot(data = employeeData, mapping = aes(x = MonthlyIncome *12, y = YearsAtCompany)) + 
  geom_point(size = 1, color="black") +
  geom_smooth(method = lm, col='red', level=0.99, formula = y ~ x) +
  
  
  labs(title = "Annual Income and Years at Company", x="Annual Income", y="Years at Company") + hw



```
```{r}
attr_grp <- employeeData %>% 
  group_by(Attrition, Department) %>% 
  summarize(mean = mean(round(MonthlyIncome),2))
attr_grp
```

```{r}
employeeData %>% group_by(Attrition) %>% summarize(N = n()) %>%
  ggplot(aes(Attrition, N, fill = Attrition)) +
  geom_col() +
  theme_bw() + 
  scale_fill_brewer(palette="Set1") + 
  # geom_text(aes(label = N), size = 5, vjust = 1.2, color = 'purple) + 
  ggtitle("Count of Employee Attrition") + 
  theme(plot.title = element_text(face = "bold", hjust = 0.5, size = 15)) +
  labs(x = "Attrition", y = "Count") + hw
```

```{r}
ggplot(employeeData, aes(x=Department, y=percent_rank(MonthlyIncome), fill=Attrition)) +
  geom_boxplot() + 
  ggtitle("Monthly Income Percentile by Department ") + 
  theme(plot.title = element_text(face = "bold", hjust = 0.5, size = 15)) +
  labs(x = "Department", y = "Income Percentile") + hw
```
```{r}
library(ggplot2)
ggplot(employeeData, aes(x=OverTime, y=percent_rank(MonthlyIncome), fill=Attrition)) +
  geom_boxplot() + 
  ggtitle("Monthly Income Percentile by Overtime ") + 
  theme(plot.title = element_text(face = "bold", hjust = 0.5, size = 15)) +
  labs(x = "Overtime", y = "Income Percentile") + hw
```
```{r}

library(lattice)
splom(select(employeeData, YearsInCurrentRole, PercentSalaryHike, MonthlyIncome), cex = 0.8, pch = 1) 

```

```{r}
colnames(employeeData)
```

```{r}
employeeData %>% 
  select(PerformanceRating, PercentSalaryHike,MonthlyIncome, JobSatisfaction, DistanceFromHome, TotalWorkingYears, YearsInCurrentRole, JobLevel, WorkLifeBalance) %>% 
  cor() %>% 
  corrplot::corrplot(method = "number", "upper") + hw
```

```{r}
ggplot(yes,aes(x = HourlyRate, y = TotalWorkingYears,group = Gender))+
   geom_point(color = "red",size = .7) +
   geom_point(shape = 21,fill = "red", color = "black", size = 1.5) +
   geom_point(shape = 21,fill = "red",color = 'red',size = 1.5) +
   labs(x = "Income",y = "Total Working Years",
      title="Total Working years Relationship to Income by Marital Status") + 
   facet_grid(.~ MaritalStatus ) + hw
```
```{r}
ggplot(employeeData,aes(x = JobSatisfaction, y = TotalWorkingYears,group = Gender))+
   geom_point(color = "blue",size = 1) +
   geom_point(shape = 21,fill = "blue", color = "black", size = 2.7) +
   geom_point(shape = 21,fill = "white",color = 'white',size = 1) +
   labs(x = "Total Working Years",y = "",
      title="") + 
   facet_grid(.~ Attrition )
```

